// Code generated by mockery; DO NOT EDIT.
// github.com/vektra/mockery
// template: testify

package timelock

import (
	"context"
	"time"

	mock "github.com/stretchr/testify/mock"
)

// NewMockScheduler creates a new instance of MockScheduler. It also registers a testing interface on the mock and a cleanup function to assert the mocks expectations.
// The first argument is typically a *testing.T value.
func NewMockScheduler(t interface {
	mock.TestingT
	Cleanup(func())
}) *MockScheduler {
	mock := &MockScheduler{}
	mock.Mock.Test(t)

	t.Cleanup(func() { mock.AssertExpectations(t) })

	return mock
}

// MockScheduler is an autogenerated mock type for the Scheduler type
type MockScheduler struct {
	mock.Mock
}

type MockScheduler_Expecter struct {
	mock *mock.Mock
}

func (_m *MockScheduler) EXPECT() *MockScheduler_Expecter {
	return &MockScheduler_Expecter{mock: &_m.Mock}
}

// addToScheduler provides a mock function for the type MockScheduler
func (_mock *MockScheduler) addToScheduler(op TimelockCallScheduled) {
	_mock.Called(op)
	return
}

// MockScheduler_addToScheduler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'addToScheduler'
type MockScheduler_addToScheduler_Call struct {
	*mock.Call
}

// addToScheduler is a helper method to define mock.On call
//   - op TimelockCallScheduled
func (_e *MockScheduler_Expecter) addToScheduler(op interface{}) *MockScheduler_addToScheduler_Call {
	return &MockScheduler_addToScheduler_Call{Call: _e.mock.On("addToScheduler", op)}
}

func (_c *MockScheduler_addToScheduler_Call) Run(run func(op TimelockCallScheduled)) *MockScheduler_addToScheduler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 TimelockCallScheduled
		if args[0] != nil {
			arg0 = args[0].(TimelockCallScheduled)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScheduler_addToScheduler_Call) Return() *MockScheduler_addToScheduler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockScheduler_addToScheduler_Call) RunAndReturn(run func(op TimelockCallScheduled)) *MockScheduler_addToScheduler_Call {
	_c.Run(run)
	return _c
}

// delFromScheduler provides a mock function for the type MockScheduler
func (_mock *MockScheduler) delFromScheduler(op operationKey) {
	_mock.Called(op)
	return
}

// MockScheduler_delFromScheduler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'delFromScheduler'
type MockScheduler_delFromScheduler_Call struct {
	*mock.Call
}

// delFromScheduler is a helper method to define mock.On call
//   - op operationKey
func (_e *MockScheduler_Expecter) delFromScheduler(op interface{}) *MockScheduler_delFromScheduler_Call {
	return &MockScheduler_delFromScheduler_Call{Call: _e.mock.On("delFromScheduler", op)}
}

func (_c *MockScheduler_delFromScheduler_Call) Run(run func(op operationKey)) *MockScheduler_delFromScheduler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 operationKey
		if args[0] != nil {
			arg0 = args[0].(operationKey)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScheduler_delFromScheduler_Call) Return() *MockScheduler_delFromScheduler_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockScheduler_delFromScheduler_Call) RunAndReturn(run func(op operationKey)) *MockScheduler_delFromScheduler_Call {
	_c.Run(run)
	return _c
}

// dumpOperationStore provides a mock function for the type MockScheduler
func (_mock *MockScheduler) dumpOperationStore(now func() time.Time) {
	_mock.Called(now)
	return
}

// MockScheduler_dumpOperationStore_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'dumpOperationStore'
type MockScheduler_dumpOperationStore_Call struct {
	*mock.Call
}

// dumpOperationStore is a helper method to define mock.On call
//   - now func() time.Time
func (_e *MockScheduler_Expecter) dumpOperationStore(now interface{}) *MockScheduler_dumpOperationStore_Call {
	return &MockScheduler_dumpOperationStore_Call{Call: _e.mock.On("dumpOperationStore", now)}
}

func (_c *MockScheduler_dumpOperationStore_Call) Run(run func(now func() time.Time)) *MockScheduler_dumpOperationStore_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 func() time.Time
		if args[0] != nil {
			arg0 = args[0].(func() time.Time)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScheduler_dumpOperationStore_Call) Return() *MockScheduler_dumpOperationStore_Call {
	_c.Call.Return()
	return _c
}

func (_c *MockScheduler_dumpOperationStore_Call) RunAndReturn(run func(now func() time.Time)) *MockScheduler_dumpOperationStore_Call {
	_c.Run(run)
	return _c
}

// runScheduler provides a mock function for the type MockScheduler
func (_mock *MockScheduler) runScheduler(ctx context.Context) <-chan struct{} {
	ret := _mock.Called(ctx)

	if len(ret) == 0 {
		panic("no return value specified for runScheduler")
	}

	var r0 <-chan struct{}
	if returnFunc, ok := ret.Get(0).(func(context.Context) <-chan struct{}); ok {
		r0 = returnFunc(ctx)
	} else {
		if ret.Get(0) != nil {
			r0 = ret.Get(0).(<-chan struct{})
		}
	}
	return r0
}

// MockScheduler_runScheduler_Call is a *mock.Call that shadows Run/Return methods with type explicit version for method 'runScheduler'
type MockScheduler_runScheduler_Call struct {
	*mock.Call
}

// runScheduler is a helper method to define mock.On call
//   - ctx context.Context
func (_e *MockScheduler_Expecter) runScheduler(ctx interface{}) *MockScheduler_runScheduler_Call {
	return &MockScheduler_runScheduler_Call{Call: _e.mock.On("runScheduler", ctx)}
}

func (_c *MockScheduler_runScheduler_Call) Run(run func(ctx context.Context)) *MockScheduler_runScheduler_Call {
	_c.Call.Run(func(args mock.Arguments) {
		var arg0 context.Context
		if args[0] != nil {
			arg0 = args[0].(context.Context)
		}
		run(
			arg0,
		)
	})
	return _c
}

func (_c *MockScheduler_runScheduler_Call) Return(valCh <-chan struct{}) *MockScheduler_runScheduler_Call {
	_c.Call.Return(valCh)
	return _c
}

func (_c *MockScheduler_runScheduler_Call) RunAndReturn(run func(ctx context.Context) <-chan struct{}) *MockScheduler_runScheduler_Call {
	_c.Call.Return(run)
	return _c
}
