all: false

packages:
  github.com/smartcontractkit/timelock-worker/pkg/timelock:
    interfaces:
      Scheduler:
        config:
          dir: "./pkg/timelock"
          filename: "scheduler_mock.go"

  github.com/ethereum/go-ethereum/accounts/abi/bind:
    interfaces:
      ContractBackend:
        config:
          dir: "./pkg/timelock/mocks"
          filename: "contract_backend.go"
