version: "3.5"

services:
  worker:
    build:
      context: ../
      dockerfile: builds/Dockerfile
    ports:
      - "8080:8080"
      - "2120:2120"
    expose:
      - 8080
      - 2120
    volumes:
      - "../${ENV_FILE}:/app/timelock.env:ro"
      - "../.tmp:/tmp"
    networks:
      - worker
    restart: unless-stopped

networks:
  worker:
    name: worker
    driver: bridge
