global:
  scrape_interval: 15s 

scrape_configs:
  - job_name: 'prometheus'
    # Override the global default and scrape targets from this job every 5 seconds.
    scrape_interval: 5s
    static_configs:
      # Target the worker network on port 2120
      - targets: ['worker:2120']
