name: Build

on:
  push:
    paths:
      - "cmd/**"
      - "pkg/**"
      - ".github/workflows/build.yml"

jobs:
  build_bif:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@11bd71901bbe5b1630ceea73d27597364c9af683 # v4.2.2

      - uses: smartcontractkit/tool-versions-to-env-action@aabd5efbaf28005284e846c5cf3a02f2cba2f4c2 # v1.0.8
        id: tool-versions

      - name: Setup go ${{ steps.tool-versions.outputs.golang_version }}
        uses: actions/setup-go@3041bf56c941b39c61721a86cd11f3bb1338122a # v5.2.0
        with:
          go-version: ${{ steps.tool-versions.outputs.golang_version }}

      - name: Make build
        run: make build

      - name: Make clean
        run: make clean
