name: Build

on:
  push:
    paths:
      - "cmd/**"
      - "pkg/**"
      - ".github/workflows/build.yml"

jobs:
  build_bif:
    name: Build
    runs-on: ubuntu-latest
    steps:
      - name: Checkout repository
        uses: actions/checkout@0ad4b8fadaa221de15dcec353f45205ec38ea70b # v4.1.4

      - uses: smartcontractkit/tool-versions-to-env-action@aabd5efbaf28005284e846c5cf3a02f2cba2f4c2 # v1.0.8
        id: tool-versions

      - name: Setup go ${{ steps.tool-versions.outputs.golang_version }}
        uses: actions/setup-go@0a12ed9d6a96ab950c8f026ed9f722fe0da7ef32 # v5.0.2
        with:
          go-version: ${{ steps.tool-versions.outputs.golang_version }}

      - name: Make build
        run: make build

      - name: Make clean
        run: make clean
