name: Verify code

on:
  push:
    paths:
      - "**.go"

jobs:
  golang_lint:
    name: Golang Lint
    runs-on: ubuntu-latest
    steps:
      - name: Checkout sources
        uses: actions/checkout@692973e3d937129bcbf40652eb9f2f61becf3332 # v4.1.7

      - uses: smartcontractkit/tool-versions-to-env-action@aabd5efbaf28005284e846c5cf3a02f2cba2f4c2 # v1.0.8
        id: tool-versions

      - name: Setup go ${{ steps.tool-versions.outputs.golang_version }}
        uses: actions/setup-go@0c52d547c9bc32b1aa3301fd7a9cb496313a4491 # v5.0.0
        with:
          go-version: ${{ steps.tool-versions.outputs.golang_version }}

      - name: golangci-lint
        uses: golangci/golangci-lint-action@9d1e0624a798bb64f6c3cea93db47765312263dc # v5.1.0
        with:
          version: v${{ steps.tool-versions.outputs.golangci-lint_version }}
          args: -v --timeout=5m
          only-new-issues: true
